clone:
  git:
    image: plugins/git
    tags: true

pipeline:
  build:
    image: ubuntu
    position: preBuild
    commands:
      - echo "this is a pr"
      - printenv
    when:
      event: [failure,success]

  trigger-test:
    when:
      branch:
        - master
        - feature/*
    image: registry.airwallex.com/alpine-curl:latest
    pull: true
    commands:
      - echo "this will run each time"
      - printenv
  run:
    image: docker:git
    commands:
      - echo "my=$$(git describe)" > abc
      - cat abc
